### ISSUE TITLE
Check for reserved keywords

### ISSUE THREAD

**Issue by beatgeb** [namics/generator-nitro#101]
A few times I hit the situation that I used a reserved javascript keyword as property name or decorator name.
To find the error was quite difficult.
Nice would be a checker to prevent using of reserved keywords or generally used method names.
Or at least to prevent in the generator using reserved keywords as pattern or decorator names.

https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Lexical_grammar could be a starting point.
In our case it was 'Map' which we wanted to add as decorator. But map is a prototype method and therefore conflicted.

**Comment by ernscht** [comment]
I'm not sure if this really is nitro related, but maybe i misunderstand you.
It is possible without problems to create patterns (including decorators and modifiers) with the names `map`, `delete`, `new`, ... and they work as expected.

The only issue i discovered was TerrificJS related: The decorator `Map` has to be written in lowercase to be startable by TerrificJS (`data-t-decorator="map"` works)

In any case i support you: avoiding reserved keywords in JavaSript contexts is good practice. But i can't imagine how we can support this well with nitro.

**Comment by ernscht** [comment]
any update on this?

**Comment by beatgeb** [comment]
I'll try to find a solution in terrific.js for JavaScript API names.
See https://developer.mozilla.org/en-US/docs/Web/API .

**Comment by ernscht** [comment]
Closing this issue here only means: issue is not nitro related.
Will contact you personally.
