### ISSUE TITLE
Pattern file name text is partially duplicated if you use "component" in the name

### ISSUE THREAD

**Issue by SimonHarte** [namics/generator-nitro#102]
If you generate a new component with a name of for example "Test Component" the resulting file name will be `testtestcomponent.{hbs|scss|etc}`, i.e. everything except "component" is duplicated.

Testing results:

- `? What's the name of your pattern? Test Component` -> `testtestcomponent.hbs`
- `? What's the name of your pattern? SomeComponent` -> `somesomecomponent.hbs`
- `? What's the name of your pattern? thirdcomponent` -> `thirdthirdcomponent.hbs`
- `? What's the name of your pattern? Test Component Pattern` -> `testtestcomponentpatternpattern.hbs`
- `? What's the name of your pattern? somecomponentpattern` -> `somesomecomponentpatternpattern.hbs`

This appears to happen only with the file name, any other place the pattern name is correct (`T.Module.SomeComponent`, `.m-some-component {}`).

**Comment by ernscht** [comment]
This is because `pattern`, `component`, `modifier` and `decorator` have a special meaning. These strings are replaced in filenames of the blueprints with desired pattern name (or decorator, modifier name)
Maybe I can improve this.

**Comment by ernscht** [comment]
Solved with additional validation for pattern names - published in release 1.2.2
