### ISSUE TITLE
Remove "required" from the schema.json blueprint.

### ISSUE THREAD

**Issue by floriangaechter** [namics/generator-nitro#103]
Do we really need to have "required" in the blueprint? Because since no properties are actually required within the default pattern implementation it always throws an error. I propose we remove it and add a link and/or a notice to the json schema documentation in our documentation.

**Comment by ernscht** [comment]
hi flo

The intention was to force that the developers get to know something about [json-schema](http://json-schema.org/) and the required attribute ;-)
But maybe something else would make more sense.

The error occures only if you use the untouched blueprint files and that is not the best idea anyway.

There is already a small description in the [Readme.md](https://github.com/namics/generator-nitro/blob/master/generators/app/templates/project/docs/nitro.md#creating-patterns)

So, should we remove the `required` property, Whats about other properties?
More ideas/opinions?

**Comment by floriangaechter** [comment]
Hey Ernscht

I can live with your reasoning behind leaving the `required` property in the blueprint.

Thanks for your explanation!
