### ISSUE TITLE
How can I have two instances of nitro run simultaneously?

### ISSUE THREAD

**Issue by ernscht** [namics/generator-nitro#11]
... or, where to configure the process.env variables?
'PORT=8000 PROXY=8001 gulp develop' deos not seem to be working (on Windows)

**Comment by brunschgi** [comment]
I think there should be an option to add an environment config, e.g. /config/brunschgi.json or /config/<servername>.json. This would make things more transparent as the configs for the staging or production environment could also be part of the repository.

**Comment by ernscht** [comment]
Windows Usage documented in README.
Environment config discussion moved to issue #27
