### ISSUE TITLE
run `yo nitro --skipInstall` cause error

### ISSUE THREAD

**Issue by smollweide** [namics/generator-nitro#124]
Error message is:
`Trying to copy from a source that does not exist: .../node_modules/nitro-exporter/README.md`
This happens because the node_modules directory don't exist in this case.
So maybe we should download `nitro-exporter` and copy it from there?

**Comment by ernscht** [comment]
thanks for the input.

I would ignore this. 
It doesn't break something, it's just a red log message ;-)
The only impact:
There is no additional documentation if you have enabled the "exporter" or "release" functionality.

**Comment by smollweide** [comment]
I'm fine with your approach. Should use a warning instead?
Btw. this log message also occurs if you add `--exporter=false` [(PR-123](https://github.com/namics/generator-nitro/pull/123) required)

**Comment by ernscht** [comment]
I know, `--exporter=false` does not work at all, but this is a different story. (It is because there is no support for boolean options like this in yo. I noticed this during testing. I remember now why we didn't implement the cli support for all booleans - It was a bit too early to merge the PR ;-)

**Comment by ernscht** [comment]
Nevertheless #124 improves readme downloads ;-)
