### ISSUE TITLE
Error: Unhandled "error" event. (Invalid or unsupported zip format. No END header found)

### ISSUE THREAD

**Issue by raimens** [namics/generator-nitro#134]
I get this error when I'm trying to install.
"Error: Unhandled "error" event. (Invalid or unsupported zip format. No END header found)"
even with:
npx -p yo -p generator-nitro@latest -- yo nitro --name=myproject --pre=less --templateEngine=hbs --clientTpl

and

yo nitro --name=myproject --pre=less --templateEngine=hbs --clientTpl

**Comment by ernscht** [comment]
I don't get an error now with
`npx -p yo -p generator-nitro@latest -- yo nitro --name=myproject --pre=less --templateEngine=hbs --clientTpl`

Some questions to narrow down the problem:
* what node & npm version do you use?
* when did you try the generator? (recently github had some problems with reachability)
* do you have a more detailed error log?
