### ISSUE TITLE
Improve chunk names in webpack config

### ISSUE THREAD

**Issue by jantimon** [namics/generator-nitro#152]
## Type of issue

* Feature

The issue refers to the:

* nitro webpack config (@nitro/webpack)

----

## Expected behavior

The Browser file cache for chunks should only be invalidated if the source code changes 

## Current behavior

Right now the chunk files include the build hash which changes every time for all files even if the code is the same

https://github.com/namics/generator-nitro/blob/8a9c32d9e79f71700f7716fd8fb8a5e1ada0caf1/packages/nitro-webpack/webpack-config/webpack.config.prod.js#L51

## Suggestions: 

We could use [contenthash] which is file content dependent so for example vendor file names would stay the same and don’t have to be downloaded as long as you don’t update the vendor libraries

**Comment by ernscht** [comment]
thank you. will look at it after my holidays.

**Comment by ernscht** [comment]
Still earlier ;-)

Contenthash would be right here, therefore I rate it as a bug. All other assets already use the "contenthash". Thank you for this report.

Will change that as default. Until then the configuration can simply be done by yourself in '/config/webpack/webpack.config.prod.js'. Simply add:

`webpackConfig.output.chunkFilename = 'js/[name]-[contenthash:7].min.js';`
