### ISSUE TITLE
Readd typescript feature for generated project

### ISSUE THREAD

**Issue by ernscht** [namics/generator-nitro#153]
## Type of issue

* Feature request

The issue refers to the:

* generator (generator-nitro)

## Description

Three year ago we removed the typescript option in the generator ( #79 ).
It's time to readd. 
* add "js" option in generator
* new example project (project-nitro-typescript)

Using typescript as default is planned for version 5)

**Comment by ernscht** [comment]
released with 4.14.0

**Comment by janwidmer** [comment]
Cool thanks
