### ISSUE TITLE
Tidy up Readme's

### ISSUE THREAD

**Issue by brunschgi** [namics/generator-nitro#16]
At the moment there are 2 Readme's:
* /README.md
* /app/templates/README.md

All of the application relevant stuff should be moved to /app/templates/README.md. The global README should only contain generator stuff.

**Comment by ernscht** [comment]
I suggest using `/app/templates/README.md` for the main description of the project ( maybe like the example on github: https://github.com/namics/frontend-defaults/blob/master/doc/README.md )
- and to move the application usage README to `/app/templates/project/docs/NITRO_README.md`

* /README.md (Generator README)
* /app/templates/README.md (Main README for the project)
* /app/templates/project/docs/NITRO_README.md (Nitro README)

**Comment by deniaz** [comment]
I've split the information according to @ernscht's comment:

* `/README.md`: Generator information, [see here](https://github.com/namics/generator-nitro/blob/develop/README.md)
* `/app/templates/README.md`: adapted README template (translated from [frontend-defaults](https://github.com/namics/frontend-defaults/blob/master/doc/README.md)), [see here](https://github.com/namics/generator-nitro/blob/develop/app/templates/README.md)
* `/app/templates/USAGE.md`: Information on how to use `yo` generators, `gulp` tasks and on how to customize a Nitro app, [see here](https://github.com/namics/generator-nitro/blob/develop/app/templates/USAGE.md)

Thoughts?
