### ISSUE TITLE
Load scripts in head with defer-attribute

### ISSUE THREAD

**Issue by jegli** [namics/generator-nitro#169]
## Type of issue

* Feature request

The issue refers to the:

* generator (generator-nitro)
* example nitro project (project-nitro)
* example nitro project with twig engine (project-nitro-twig)
* example nitro project with typescript jsCompiler (project-nitro-typescript)

## Background

A while ago @dmodalek talked about the advantages of loading scripts within the head with the defer attribute. I noticed that nitro-projects are generated with the scripts at the end of the body. I propose that generated projects have the script-tag in the head with the defer attribute. Defer has [browser-support down to IE10](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#Browser_compatibility) and brings a performance gain because the [script can be downloaded while the HTML is being parsed](https://flaviocopes.com/javascript-async-defer/).

**Comment by ernscht** [comment]
This is a really good improvement of the project bootstrap. Thank you very much for your clean work.

**Comment by ernscht** [comment]
This is a good improvement of the project bootstrap. Performance measurements will benefit from it. Nevertheless, it must be decided in the project whether defer will be used in this way. The loading behavior of the page cannot have the desired effect with older browsers, for example.
