### ISSUE TITLE
Enhance svg sprites to support icon sources from different folders per svgSprites object src

### ISSUE THREAD

**Issue by janwidmer** [namics/generator-nitro#180]
## Type of issue

* Feature request

The issue refers to the:

* nitro gulp tasks (@nitro/gulp)
* example nitro project (project-nitro)
* example nitro project with twig engine (project-nitro-twig)
* example nitro project with typescript jsCompiler (project-nitro-typescript)
* example nitro project using "light" server for production preview (project-prod)

**Comment by ernscht** [comment]
great. thank you.
merged into develop.
