### ISSUE TITLE
404 page with view listing

### ISSUE THREAD

**Issue by brunschgi** [namics/generator-nitro#19]
To make the 404 page more useful, it would be nice if all views are listed.

Our proposal is:
* Create handlebars helper for listing all pages
* Create a default 404.html in /views/
* Make use of the listing helpers in 404.html

This makes the 404 page customizable for each project, but it comes with a wise default.

**Comment by deniaz** [comment]
I have added a `{{view_list}}` helper [here](https://github.com/namics/generator-nitro/blob/develop/app/templates/app/helpers/view_list.js) and a default `404` page [here](https://github.com/namics/generator-nitro/blob/develop/app/templates/views/404.html). The `router` tries to render the `404` view when no view was found (see [here](https://github.com/namics/generator-nitro/blob/develop/app/templates/app/core/router.js#L116)).

The functionality is done, but it looks horrible out of the box. Shall we do something about that? With some styles from the project itself it should look alright, though.

**Comment by ernscht** [comment]
The look we can ignore, I think.
But the view_list helper should list all views except the 404 page.

The point is, there may be [subfolders](https://github.com/namics/generator-nitro/blob/develop/app/templates/project/docs/nitro.md#creating-pages) and it would be great to have some sort of structured list of all views. e.g.
```
<ul>
<li><a href="index">Index</a>
<li><a href="content">Content</a>
<li><h2>Content</h2>
    <ul>
        <li><a href="content-variant">Content Variant</a><li>
```
Do you see a way to achieve that?

**Comment by deniaz** [comment]
Sure, I'll look into it today or tomorrow.

**Comment by deniaz** [comment]
Commit 20b0138 does that, with the exception of the nested `ul`. That would be possible, but would require to store the views in a data structure rather than a flat list.

Currently we have something like:

```js
var results = [
  {
    view_name: "index",
    url: "index"
  },
  {
    view_name: "bar",
    url: "foo-bar"
  }
];
```

We'd have to change that to a tree and parse the tree upon rendering.
Something like:

```js
var results = [
  {
    view_name: "index",
    url: "index"
  },
  {
    sub_name: "foo",
    views: [
        {
          view_name: "bar",
          url: "foo-bar"
        },
        {
          view_name: "baz",
          url: "foo-baz"
        }
    ]
  }
];
```

I'm not sure whether that's a real benefit, therefore I suggest to keep the current solution and close this issue?

**Comment by deniaz** [comment]
Well I'm just going ahead and close the issue, if you'd rather have the tree-structure just reopen @ernscht ;)
