### ISSUE TITLE
Restructure Gulp Tasks

### ISSUE THREAD

**Issue by brunschgi** [namics/generator-nitro#22]
Make the naming of the gulp tasks and their dependencies more convenient.

**Comment by ernscht** [comment]
* gulp task `production` should use the minified version of the assets
* gulp task `production` will be used for the prototype view and therefore it should be ensured that the server always is on (e.g. with [forever](https://www.npmjs.com/package/forever))
* there could be an additional gulp task witch gives a temporary public url for testing purposes (e.g. [ngrok](https://www.npmjs.com/package/ngrok))

**Comment by SimonHarte** [comment]
It would also be more convenient, if gulp tasks would be split up into separate task files which then get aggregated. Something like [unic did](https://github.com/unic/estatico/tree/develop/gulp), I'm currently working on this in another project myself (updating it in a generated project).

**Comment by brunschgi** [comment]
I already began with the implementation of this task. No worry – the tasks will be splitted up in separate task files ;-)  Although our approach is a little bit different than the approach mentioned above.

**Comment by ernscht** [comment]
Useless task `production` was removed. 
Typically, a production server needs more control.

**Comment by deniaz** [comment]
Sorry, didn't mean to reopen. Just wanted to say that there are a few servers actually using the task.. Might run into the "update"-issue we've discussed on Thursday..?
