### ISSUE TITLE
Replace gulp-express with gulp-live-server

### ISSUE THREAD

**Issue by deniaz** [namics/generator-nitro#28]
`gulp-express` issues a warning upon installation:

![screen shot 2015-06-15 at 14 16 03](https://cloud.githubusercontent.com/assets/698963/8159692/75c4bd2c-1369-11e5-9b3d-d9268884ada6.png)

> please use [gulp-live-server](https://www.npmjs.com/package/gulp-live-server) instead, it's a new version of `gulp-express` with a better name and new features. -- [github.com/gimm/gulp-express](https://github.com/gimm/gulp-express)

I haven't checked whether it's a drop-in replacement or needs adjustments.

**Comment by ernscht** [comment]
could be part of #22
