### ISSUE TITLE
View Service

### ISSUE THREAD

**Issue by deniaz** [namics/generator-nitro#34]
Introduce a `ViewService` which knows about Nitro's views. 
This can be some sort of a flat list (or a tree, see [#19](https://github.com/namics/generator-nitro/issues/19#issuecomment-113436873)) which then can be used in the `view_list` helper ([here](https://github.com/namics/generator-nitro/blob/develop/app/templates/app/helpers/view_list.js)) and the `router` ([here](https://github.com/namics/generator-nitro/blob/develop/app/templates/app/core/router.js)).

Performance-wise it might be a tad slower than the current implementation but a lot more readable. See [here](https://github.com/namics/generator-nitro/blob/develop/app/templates/app/core/router.js#L20).

Ideally the list doesn't need to be recalculated on every request but can be cached. This might introduce new issues when creating/deleting/renaming views, but should be solvable. 

Maybe this can be somehow integrated with express/hbs?

**Comment by ernscht** [comment]
now we have a lil helper for views - bit more readable (470de26395b656842568746f734695e8d2bd1aca)

will close now.
