### ISSUE TITLE
Clean Up (dev)-dependencies

### ISSUE THREAD

**Issue by deniaz** [namics/generator-nitro#35]
We should have another look at the `dependencies` and `devDependencies` to clean up and categorize.

**Comment by deniaz** [comment]
see #22

**Comment by ernscht** [comment]
@deniaz what do you think about this: https://github.com/namics/generator-nitro/commit/673b68778b7e085a5df87acde1cdb81a277080e5

**Comment by ernscht** [comment]
I'll close this. But if you think this needs more work don't be afraid to open the task again.
