### ISSUE TITLE
yo nitro:component ignores "-" in created filenames

### ISSUE THREAD

**Issue by jackblackCH** [namics/generator-nitro#41]
try

```$ yo nitro:component```

```$ What's the name of your component? nav-main```

the hyphen is correctly used for the directory name but not for the file names of views, js and less files.
resulting filenames: navmain.ext instead of nav-main.ext

**Comment by ernscht** [comment]
Thanks for your input

`Yo nitro:component` works like defined. Template filenames [shouldn't have hyphens](https://github.com/namics/generator-nitro/blob/master/spec/componentSpec.js#L170).
 
But there was a bug in the component helper which didn't loaded the generated template file.

Does that help you, too?

**Comment by jackblackCH** [comment]
It works yes.. but isn't it more convenient to use BEM style also for the module file naming?
BEM uses two hyphens for modifiers that you still can use a hyphen in your module name.
And even you decide to avoid hyphens in module file names, why then you apply it to the directory?

**Comment by ernscht** [comment]
BEM means Block-Element-Modifier, so this does not fit particularly well for file names ;-)
For file & folder names we follow the principles of simplicity and requirements of integrations.

From this perspective, there is nothing against the use of hyphens in file names for views, js and css. It's a bit different for data files. However, it depends on the type of integration and was the reason for the current implementation.

But. We can do this change. This means:
Hyphens are no longer deleted in file names of a component. All letters are lowercase. This also applies to the names for decorators and modifiers.

This is now planned for the next release. Pull Requests are also welcome.
