### ISSUE TITLE
Automate bower dependencies

### ISSUE THREAD

**Issue by deniaz** [namics/generator-nitro#42]
> Scenario:
> Dev A adds bower dependency, pushes code. Dev B pulls code, runs nitro and gets a broken Frontend > due to missing dependencies.

We should probably find a way how to solve that.
This ticket is more of a reminder than a bug report.

**Comment by SimonHarte** [comment]
Possible solution: https://gist.github.com/sindresorhus/7996717

**Comment by ernscht** [comment]
Thanks Simon
Works like a charm – in a [modified version](https://gist.github.com/ernscht/731f9ec710e5b3d01fa3) also on windows.
But this must be configured manually on each project.

What du you think about [git-guppy](https://www.npmjs.com/package/git-guppy) or [ghooks](https://www.npmjs.com/package/ghooks)?

**Comment by dmodalek** [comment]
Something similar: we could add a `postinstall` hook in the `package.json` to install bower dependencies automatically, after running `npm install`.
```bash
"scripts": {
    "postinstall" : "bower install"
}
```

**Comment by ernscht** [comment]
This git hook should solve this:
https://github.com/namics/generator-nitro/blob/master/app/templates/project/.githooks/post-merge
As default it will be installed with `npm install`
