### ISSUE TITLE
Nitro crashes if "spec" folder is deleted

### ISSUE THREAD

**Issue by floriangaechter** [namics/generator-nitro#47]
Nitro crashes with following error message:
```
…/node_modules/gulp-watch/node_modules/glob/node_modules/minimatch/minimatch.js:108
    throw new TypeError('glob pattern string required')
          ^
TypeError: glob pattern string required
…
```

**Comment by ernscht** [comment]
known issue witch current version of gulp-watch: https://github.com/floatdrop/gulp-watch/issues/187.

we can't fix the issue but we will exclude the spec folder from watching anyway
