### ISSUE TITLE
Make view file extension configurable

### ISSUE THREAD

**Issue by SimonHarte** [namics/generator-nitro#54]
The default file extension for templates is currently `.html`, it would be great if you could easily switch this to `.hbs` on project setup, just for better syntax highlighting.

**Comment by deniaz** [comment]
This has already been discussed here #40.
Nitro came with this since the very first version.

**Comment by SimonHarte** [comment]
What I meant is that you get a selection of file extensions when using `yo nitro` (same as when you get asked if you want to use less or scss) and then initial files would already be created with this extension. Currently you need to adjust the config afterwards and change extensions manually.

Also the setting in `config.json` doesn't seem to affect the use of `yo nitro:component`, which will still generate html files, so there seems to be some optimisation potential with this.

**Comment by ernscht** [comment]
You are right, having a yeoman option to configure the view file extension would be nice but we have not highly prioritized this. Maybe we come back to this later – there are other options planned ( #37 #46 #30 ). Also a PR would be welcome ;-)

For now, you have to configure it manually and additionally you should change the file extension of your [component blueprints](https://github.com/namics/generator-nitro/tree/master/app/templates/project/blueprints/component). Use your desired extension name in your blueprints and you will get the right files.

**Comment by SimonHarte** [comment]
Well I'd gladly look into this and make a PR, I'll probably have some time for it during the next weeks.

**Comment by deniaz** [comment]
I'm only here to remind people with time of #46 ;) There are a few other ideas to extend the generator.

**Comment by ernscht** [comment]
thank you
