### ISSUE TITLE
Idea Pool

### ISSUE THREAD

**Issue by deniaz** [namics/generator-nitro#57]
Ideas how to further develop Nitro which are not simple to implement. Concepts and ideas need to be developed further..
- Break nitro into packages (app, gulp, generator)
- Nitro **app** should be installable via `npm install` but still extendable
- [More Ideas](https://github.com/namics/generator-nitro/issues?q=is:issue+is:open+label:idea)

**Comment by dmodalek** [comment]
For the Frontend Handover to an external partner the following extensions could be useful:

1. Overview of all Views and Components (Atoms, Molecules etc). An Icon next to each View and Component which indicates if the Components is "ready". The following example is from the Sunrise project:
<img width="556" alt="screen shot 2016-02-18 at 13 12 18" src="https://cloud.githubusercontent.com/assets/845184/13143001/46cd4c3c-d641-11e5-9164-111db3432bb0.png">

2. Component Detail Views which shows all Component Variations and maybe a Code preview where oe can copy the HTML, CSS and JS. The following example is from the SUVA project:
<img width="1101" alt="screen shot 2016-02-18 at 13 12 56" src="https://cloud.githubusercontent.com/assets/845184/13143019/5cdf0998-d641-11e5-896e-f173ed4c8fac.png">

3. A static Export of the Frontend. As far as I know, @Regaddi is working on this?

What do you @deniaz and @ernscht think of those ideas? Is this something that could be part of Nitro in the future or should it better be developed on a per project basis?

**Comment by ernscht** [comment]
@dmodalek – all meaningful things ;-)
These features were discussed on several occasions and are naturally desired.
Some features I would try to integrate and some not (different repo & npm package, ...).
We started with the static export to gain experience but help would always be welcome. I think we should meet in the near future. You hear from us.

**Comment by SimonHarte** [comment]
What do you think about a sub-generator for modifiers and decorators? I know that you can add those after creating a component by using `yo nitro:component` again but this will prompt you for overwriting the existing files. A separated generator for both could simplify the process a lot and it could even prompt you the existing components for selection.

**Comment by ernscht** [comment]
@SimonHarte interesting idea. We should handle this idea with #46.

**Comment by ernscht** [comment]
since nitro 4 is released now, we start a new idea pool.
