### ISSUE TITLE
Simplify LESS/SCSS component patterns by using parent selector

### ISSUE THREAD

**Issue by SimonHarte** [namics/generator-nitro#60]
Currently the boilerplate LESS/SCSS files repeat `.m-example` for every element, this could be simplified by using the `&` parent selector and thus leading developers towards an imho better pattern for structuring the code.

**Current SCSS**
```
.m-example {
	padding: 1em 2em;
	background: darken($gray, 15%);
}
.m-example__headline {
	font-size: 1.6em;
	color: white;
}
.m-example__link {
	color: white;
}
```

**Optimised SCSS**
```
.m-example {
	padding: 1em 2em;
	background: darken($gray, 15%);

	&__headline {
		font-size: 1.6em;
		color: white;
	}

	&__link {
		color: white;
	}
}
```

**Comment by ernscht** [comment]
Hi Simon.
That's a matter of taste. There are arguments for both.
I recommend not using the  `&` parent selector, because the source code remains better searchable.
But feel free to change this in your project.

**Comment by SimonHarte** [comment]
Yeah I would have labelled this as "Idea", if I could.
