### ISSUE TITLE
Remember user inputs

### ISSUE THREAD

**Issue by SimonHarte** [namics/generator-nitro#61]
Most of us probably use the same technologies throughout different projects so it would make sense to remember seletions when you chose for example `scss` and `Typescript` for your first project and give those as defaults when rerunning `yo nitro` in another project.

This should actually be pretty easy to implement: http://yeoman.io/authoring/user-interactions.html

**Comment by ernscht** [comment]
using `store` seems to be a good idea

**Comment by ernscht** [comment]
PR #63 merged
