### ISSUE TITLE
Add option to not scaffold the example module and other example files

### ISSUE THREAD

**Issue by floriangaechter** [namics/generator-nitro#64]
If you're familiar with nitro you don't need the whole example-stuff. It would be nice to have an option to not scaffold them when generating a new project.

**Comment by SimonHarte** [comment]
I guess rather the reversed case where it asks you if you want to generate example stuff with default set to `no`?

**Comment by SimonHarte** [comment]
Would you say the default is *to have* or *not to have* the examples?

**Comment by ernscht** [comment]
i prefer to include the examples as default.
by remembering the user input #61 this seems to be the best for both use cases ;-)

which files exactly should be excluded?

**Comment by floriangaechter** [comment]
After examining the current solution (with only the example module being generated) I think we can live with that.
