### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by Regaddi** [namics/generator-nitro#67]
When executing `yo nitro` on node >=5:

    npm WARN deprecated i18next-client@1.10.3: you can use npm install i18next from version 2.0.0
    npm WARN deprecated gulp-minify-css@1.2.3: Please use gulp-cssnano instead.

There are also other deprecated warnings, but these seem to come from used packages.

**Comment by ernscht** [comment]
i suppose you are using an outdated release of nitro.
gulp-minify-css was replaced by gulp-cssnano in release 0.2.2 on 1 January.

Updating i18next is a big thing. As long as it works well I'd not do that till. (Except someone has a lot of time ;-)

and anyway – using node >=5 is [not recommended nor tested](https://github.com/namics/generator-nitro#usage)

**Comment by deniaz** [comment]
The build matrix in [`.travis.yml`](https://github.com/namics/generator-nitro/blob/master/.travis.yml) is always a good place to check for supported versions.

```yml
node_js:
  - '4'
  - '0.12'

**Comment by deniaz** [comment]
oh, btw, might be the wrong ticket but stating version '4' tests against the latest version (4.3.0 in this case). Since 4.2 is LTS it might make sense to explicitly test against? @ernscht

**Comment by ernscht** [comment]
The current LTS version is 4.3.1 [see notes](https://nodejs.org/en/blog/vulnerability/february-2016-security-releases/).
It seems to be the right way to use the major version only as the version to test against. [This chart](https://github.com/nodejs/LTS/blob/master/schedule.png) should support this approach.

**Comment by deniaz** [comment]
Welp. Of course you are absolutely right and there's nothing more to say.
