### ISSUE TITLE
Misleading error message if component template is missing

### ISSUE THREAD

**Issue by SimonHarte** [namics/generator-nitro#69]
Just encountered this issue when I called the component helper like this `{{component name="my-component" template="special"}}`.
The error message I got was `Component my-component not found.` and so I triple checked the component name because I thought it had a typo in it when in reality it was just the wrong template parameter, which I should've prefixed with the full component name.

First it would be great if you'd actually get an error which points to a missing template instead of a missing component to prevent confusion and second it's also a bit inconvenient that you have to write the component name again, couldn't this be simplified? Especially for consistency since you don't have to write the full component name in modifiers and decorators either when creating components or even setting them via data.

**Comment by ernscht** [comment]
Thanks for your feedback.

I've added a more meaningfull error message:
`Component "..." with template file "..." not found in folder "...".`
This will be in the next release.

But for the second part:
You have been warned. ;-)
![warning-different-template-files](https://cloud.githubusercontent.com/assets/149406/13121659/8bf369d8-d5b3-11e5-9a7e-52a69b9066d9.png)

I can't find anything inconvenient and the component helper works in a very simple and logical way.
You have to provide the full name without the extension for data and template files. Nobody demands that the name of the component must be included in the file name. It's just the default. And this applies to all component files. 
We shouldn't add some magic.
