### ISSUE TITLE
File names of newly created component seem inconsistent

### ISSUE THREAD

**Issue by SimonHarte** [namics/generator-nitro#71]
Maybe there should be some guidelines on how to best/properly name components (didn't find any in nitro.md yet).

If you create a component with the name "My Component" for example, you'll get the following naming:
- **Component name**: `My Component`
- **Component directory**: `MyComponent`
- **Component file name**: `mycomponent`
- **CSS selector**: `my-component`
- **JS module**: `MyComponent`

The inconsistency lies in the file name, in my opinion it should be `my-component` as well, it even says so in the inline commentaries: `file: this.name.replace(/[^A-Za-z0-9-]/g, '').toLowerCase() // Component filename, eg. main-navigation` (https://github.com/namics/generator-nitro/blob/master/component/index.js#L150).

But as you can read from the regex, a white space will just be removed instead of replaced with a dash, I think we could simply use `_.kebabCase(this.name)`, which is used for the CSS selector as well.

I could make a PR for this, if you approve.

**Comment by ernscht** [comment]
This is how it should work.
Spaces should be ignored. See the Test: https://github.com/namics/generator-nitro/blob/master/spec/componentSpec.js#L205
No change required.

**Comment by SimonHarte** [comment]
This isn't even worth some discussion? What's the exact reason for removing white spaces instead of replacing them with dashes in the sense of kebab-case (which seems more intuitive to me)?

**Comment by ernscht** [comment]
i'll call you
