### ISSUE TITLE
can we stop the support for node.js 0.12.x?

### ISSUE THREAD

**Issue by ernscht** [namics/generator-nitro#73]
Is it ok if we stop supporting node.js version 0.12.x and focus on the newer versions? Or is support for node.js 0.12.x still needed?
The latest versions of some dependencies no longer function with 0.12.x.

**Comment by floriangaechter** [comment]
According to the node website, version 0.12 ist not under LTS anymore. So I'd say we focus on 4.0 upward.

**Comment by ernscht** [comment]
so, we will ;-)
