### ISSUE TITLE
Configure generators

### ISSUE THREAD

**Issue by janbiasi** [namics/generator-nitro#88]
It would be great if you could adjust the steps of each generator. We encountered a problem with the current nitro in a project, where a needed third party library uses handlebars 3.x and nitro generated handlebars 4.x templates. So the browser will fail if the handlebars client lib detects a handlebars 4.x template generated by nitro's `yo nitro:component`.

My Input: Add the capability of a `.nitrorc` file or something similar, where you can configure the steps in the tasks. A very short example to prevent creating templates:

``` json
{
    "generator": {
        "component": {
            "generateTemplates": false
        }
    }
}
```

Any inputs?

**Comment by ernscht** [comment]
Basically, you have full controll over the generated files with your blueprint folder and the configuration in `config.json`.
The blueprints are ajustable at any time and ...
components/patterns are updateable with yo `nitro:component <name>`

So, i can't really see the advantage of such a specific configuration for this case.
Maybe it could help for other cases.

-> link to #46
