### ISSUE TITLE
ES6 Promise configuration misspelled

### ISSUE THREAD

**Issue by janbiasi** [namics/generator-nitro#89]
Every Nitro Project has an important Bug within the configuration (we noticed it in Internet Explorer 9, 10 and 11), that if a Promise is used by a newer jQuery Version or a third party dependency, the whole JavaScript will fail due an `undefinedReferenceError` which says that `Promise` has not been defined. @floriangaechter found this bug today -> there's an issue in the default configuration shipped by Nitro within the `config["app.js"]`.

```json
"app.js": [
	"assets/vendor/es6-promise/promise.min.js"
]
```

but the file `promise.min.js` does not exist and will not be included in the build, so you should adjust the default configuration to this:

```json
"app.js": [
	"assets/vendor/es6-promise/es6-promise.min.js"
]
```

**Comment by ernscht** [comment]
thank you for this finding.
0.4.4 is published and will fix this.
