### ISSUE TITLE
use standardized config system

### ISSUE THREAD

**Issue by smollweide** [namics/generator-nitro#91]
Currently it's not possible to change the ports.
Because of that the [https://github.com/namics/nitro-exporter](url) will break the export while nitro is running.

Maybe the ports should be configurable or you use [find-free-port](https://github.com/mhzed/find-free-port)

**Comment by ernscht** [comment]
I dont't get it, sorry.
Ports are configurable: [see README](https://github.com/namics/generator-nitro/blob/master/app/templates/project/docs/nitro.md#starting-the-app)

**Comment by smollweide** [comment]
It would be great to have it configurable in the "config.json/nitro". For example:
```
"nitro": {
    "port": 3000,
    "proxyPort": 3001
}
```

**Comment by ernscht** [comment]
good idea ;-)

**Comment by Regaddi** [comment]
Another idea could be to not even think about configurable ports and let nitro determine its own free port. This way you don't have to configure ports at all, if you start different instances of nitro or exporters.

This could be done with e.g. [find-free-port](https://github.com/mhzed/find-free-port)

**Comment by jantimon** [comment]
Find free port has the disadvantage that your browser autocomplete won't work as the ports would differ all the time.

**Comment by ernscht** [comment]
A "free ports" feature seems to be too much magic and dangerous (especially for serverside usage).
So, we should focus on the "node-config" topic. 
Some time ago there was not much feedback on this #27 ;-)

How would you do this? What should be configurable? Do we need environment configs, ... ?

**Comment by jantimon** [comment]
Some ideas (although some of them are already handled by the yeoman generator itself).

Well some global configurations:

 * port
 * host
 * set the copyright notice for the project
 * autoprefixer browser matrix
 
We could have some settings which might be different for dev/prod like

 * enable/disable source-maps
 * enable/disable minification

We could add some dev feature flags like:

 * enable/disable hot-module-replacement
 * enable/disable precommit linting
 * enable/disable an upload-mock
 * enable/disable an ajax-mock
 * enable/disable unit-tests
