### ISSUE TITLE
Dump views for different languages

### ISSUE THREAD

**Issue by Regaddi** [namics/generator-nitro#97]
Hey,

It'd be great, if the `dump-views` task also extracted views, when different translation files are configured. This way [nitro-exporter](https://www.npmjs.com/package/nitro-exporter) could completely rely on the `dump-views` task, when exporting views without dropping the `i18n` option.

**Comment by ernscht** [comment]
Why not ;-)
Would probably be useful if the gulp task is configurable with arguments (default should be without language variants).

**Comment by ernscht** [comment]
#98

**Comment by ernscht** [comment]
#98 was merged. thank you very much.
